name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Adding environment variables
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          request_pty: true
          envs: BOT_TOKEN,GUILD_ID,GT_ACCESS_TOKEN,GT_USERNAME,GT_REPOSITORY,MONGODB_URI,DEVELOPER_IDS,PREFIX,PORT
          script: |
            bash -lc '
              cat > /home/rws/bot/github-issue-bot/.env << EOF
              BOT_TOKEN=$BOT_TOKEN
              GUILD_ID=$GUILD_ID
              GT_ACCESS_TOKEN=$GT_ACCESS_TOKEN
              GT_USERNAME=$GT_USERNAME
              GT_REPOSITORY=$GT_REPOSITORY
              MONGODB_URI=$MONGODB_URI
              DEVELOPER_IDS=$DEVELOPER_IDS
              PREFIX=$PREFIX
              PORT=$PORT
              EOF
            '
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          GUILD_ID: ${{ vars.GUILD_ID }}
          GT_ACCESS_TOKEN: ${{ secrets.GT_ACCESS_TOKEN }}
          GT_USERNAME: ${{ vars.GT_USERNAME }}
          GT_REPOSITORY: ${{ vars.GT_REPOSITORY }}
          MONGODB_URI: ${{ secrets.MONGODB_URI }}
          DEVELOPER_IDS: ${{ vars.DEVELOPER_IDS }}
          PREFIX: ${{ vars.PREFIX }}
          PORT: ${{ vars.PORT }}

      - name: SSH & Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            . "$NVM_DIR/nvm.sh"

            nvm use 20

            cd /home/rws/bot/github-issue-bot

            echo "Pulling latest code..."
            git pull origin main

            echo "Installing deps..."
            npm ci --no-audit --no-fund

            echo "Building..."
            npm run build

            echo "Restarting PM2..."
            pm2 delete github-issue-bot || true
            pm2 start dist/index.js --name github-issue-bot

            echo "Saving PM2..."
            pm2 save

            echo "Showing PM2 status..."
            pm2 status

            echo "Done ✅"

